blog/articles/urls.py
from django.urls import path
from blog.articles.views import (articles_view, creation_article_view,
                                 update_article_view, delete_article_view)

app_name = "articles"

urlpatterns = [
    path("", articles_view, name="all-articles"),
    path("articles/creation/", creation_article_view, name="creation-article"),
    path(
        "articles/<slug:slug>/update/",
        update_article_view,
        name="article-detail-update",
    ),
    path(
        "articles/<slug:slug>/delete/",
        delete_article_view,
        name="article-detail-delete",
    ),
]

blog/contacts/urls.py
from django.urls import path

from blog.contacts.views import send_contact_message

app_name = "contacts"

urlpatterns = [
    path("contacts/message/", send_contact_message, name="contact-message"),
]

blog/events/urls.py
from django.urls import path
from blog.events.views import (events_view, creation_event_view,
                               update_event_view, delete_event_view)

app_name = "events"

urlpatterns = [
    path("events/", events_view, name="all-events"),
    path("events/creation/",
         creation_event_view,
         name="creation-event",
         ),
    path(
        "events/<slug:slug>/update/",
        update_event_view,
        name="event-detail-update",
        ),
    path(
        "events/<slug:slug>/delete/",
        delete_event_view,
        name="event-detail-delete",
        ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Configuration drf-yasg
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView)

# Configuration drf-yasg
schema_view = get_schema_view(
   openapi.Info(
      title="Blog Passion API",
      default_version='v1',
      description="An API to manage Blog Passion",
      contact=openapi.Contact(email="contact@blog-passion.fr"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.articles.urls")),
    path("events/", include("blog.events.urls")),
    path("users/", include("blog.users.urls")),
    path("contacts/", include("blog.contacts.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(),
         name='token_refresh'),
    path("", include("api.articles.urls")),
    path("", include('api.users.urls')),
    path("", include("api.events.urls")),
    path("", include("api.contacts.urls")),
    # Configuration drf-yasg
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0),
         name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0),
         name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),
         name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/fragments/nav_bar.html
{% load i18n %}
{% load static %}

<!-- Navbar -->
<nav  x-data="{ open: false }" x-on:keydown.escape="open = false" x-on:click.outside="open = false"
  class="fixed top-0 z-20 
  bg-gradient-to-b from-slate-400 to-slate-950
  md:bg-gradient-to-r 
  p-4 w-full grid grid-cols-none shadow-md md:grid-cols-menu 
  md:shadow-none md:relative md:mx-auto">

  <div class="flex justify-between items-center md:justify-center">
    <a href="#accueil">
      <img 
      src="{% static 'images/plume.png' %}" 
      alt="plume logo" 
      class="w-12">
    </a>
    <button x-on:click="open = ! open" 
    class="rounded-md p-2 ring-1 ring-slate-200 ring-opacity-20 md:hidden">
      <img src="{% static 'images/menu.svg' %}" :src="open ? '{% static 'images/cross.svg' %}' : '{% static 'images/menu.svg' %}'" 
      alt="icône hamburger" class="h-6 w-6">
    </button>
  </div>


  <ul x-cloak :class="open ? '' : 'hidden' " 
    class="flex flex-col md:flex md:pt-0 
    md:flex-row md:space-x-10 md:w-auto md:items-center md:justify-center">


    <li class="py-2 text-center border-t border-slate-200 md:border-0">
      <a 
      href="{% url 'articles:all-articles' %}"
      class="p-2 text-slate-50 text-lg font-medium hover:bg-violet-300 hover:rounded-lg"
      >Articles</a>
    </li>

    <li class="py-2 text-center border-t border-slate-200 md:border-0">
      <a 
      href="{% url 'events:all-events' %}"
      class="p-2 text-slate-50 text-lg font-medium hover:bg-violet-300 hover:rounded-lg"
      >Evénements</a>
    </li>

    <li class="py-2 text-center border-t border-slate-200 md:border-0">
      <a 
      href="{% url 'contacts:contact-message' %}"
      class="p-2 text-slate-50 text-lg font-medium hover:bg-violet-300 hover:rounded-lg"
      >Contact</a>
  </li>

  </ul>

  {% if user.is_authenticated %}
    {% comment %} Boutton Logout {% endcomment %}
    <div x-cloak :class="open ? '' : 'hidden' " class="flex justify-center items-center mt-6 md:mt-0 md:justify-end md:flex">
      <form method="post" action="{% url 'users:logout' %}">
        {% csrf_token %}
      <button type="submit" class="group relative h-11 w-36 border border-solid border-white rounded-lg bg-violet-50 font-normal text-lg text-center shadow-inner flex justify-center items-center">
        <div class="absolute  rounded-lg inset-0 w-3 bg-violet-200 transition-all duration-[250ms] ease-out group-hover:w-full">
        </div>
        <span class="relative text-black group-hover:font-medium pr-1">Logout</span>
        <svg class="relative w-6 h-6 group-hover:font-medium" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9" />
        </svg>
      </button>
    </form>
    </div>
  {% else %}
    {% comment %} Boutton Login {% endcomment %}
    <div x-cloak :class="open ? '' : 'hidden' " class="flex justify-center items-center mt-6 md:mt-0 md:justify-end md:flex">
      <a   href="{% url 'users:login' %}"  class="group relative h-11 w-36 border border-solid border-white rounded-lg bg-violet-50 font-normal text-lg text-center shadow-inner flex justify-center items-center">
        <div class="absolute  rounded-lg inset-0 w-3 bg-violet-200 transition-all duration-[250ms] ease-out group-hover:w-full">
        </div>
        <span class="relative text-black group-hover:font-medium pr-1">Login</span>
        <svg  class="relative w-6 h-6 group-hover:font-medium rotate-180" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75" />
        </svg>
      </a>
      </div>
  {% endif %}


</nav>