api/articles/urls.py
from django.urls import path, include
from rest_framework import routers

from api.articles.views import ArticleViewset, ArticleViewsetForVisitor

# Ici nous créons notre routeur
router = routers.SimpleRouter()
# Puis lui déclarons une url basée sur le mot clé "article" et notre view
# afin que l’url générée soit celle que nous souhaitons ‘/api/article/’
router.register('articles_admin', ArticleViewset, basename='articles_admin')
router.register('articles', ArticleViewsetForVisitor, basename='articles')

urlpatterns = [
    path('api/', include(router.urls))
]

blog/articles/urls.py
from django.urls import path
from blog.articles.views import (articles_view, creation_article_view,
                                 update_article_view, delete_article_view)

app_name = "articles"

urlpatterns = [
    path("", articles_view, name="all-articles"),
    path("articles/creation/", creation_article_view, name="creation-article"),
    path(
        "articles/<slug:slug>/update/",
        update_article_view,
        name="article-detail-update",
    ),
    path(
        "articles/<slug:slug>/delete/",
        delete_article_view,
        name="article-detail-delete",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Configuration drf-yasg
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView)

# Configuration drf-yasg
schema_view = get_schema_view(
   openapi.Info(
      title="Blog Passion API",
      default_version='v1',
      description="An API to manage Blog Passion",
      contact=openapi.Contact(email="contact@blog-passion.fr"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.articles.urls")),
    path("events/", include("blog.events.urls")),
    path("users/", include("blog.users.urls")),
    path("contacts/", include("blog.contacts.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(),
         name='token_refresh'),
    path("", include("api.articles.urls")),
    path("", include('api.users.urls')),
    path("", include("api.events.urls")),
    path("", include("api.contacts.urls")),
    # Configuration drf-yasg
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0),
         name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0),
         name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),
         name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/articles/models.py
from django.db import models
from django.conf import settings
from django_extensions.db.fields import AutoSlugField
from django.utils.translation import gettext_lazy as _


from PIL import Image


class Article(models.Model):
    """Each article will be registered here.
    """

    title = models.CharField(_("titre"), max_length=200)
    slug = AutoSlugField(
        "article slug",
        populate_from=["title"],
        unique=True,
    )
    content = models.TextField(_("contenu"), blank=True)
    image = models.ImageField(
        _("Image de l'article"),
        upload_to="article/images/articles",
        blank=True,
        null=True,
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="articles",
        verbose_name=_("auteur"),
    )
    published_on = models.DateField(_("publié le"), blank=True, null=True)
    published = models.BooleanField(_("publié"), default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    IMAGE_MAX_SIZE = (400, 150)

    class Meta:
        verbose_name_plural = _("articles")
        ordering = ['-published_on']

    def __str__(self):
        return self.title

    # Adaptation du format de l'image à un max définit en IMAGE_MAX_SIZE
    # A placer dans le formulaire
    def resize_image(self):
        with Image.open(self.image) as image:
            image.thumbnail(self.IMAGE_MAX_SIZE)
            image.save(self.image.path)

blog/articles/forms.py
from django import forms

# from crispy_forms.helper import FormHelper

from blog.articles.models import Article


class CreationArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = [
            "title",
            "content",
            "image",
            "published",
        ]

api/articles/views.py
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from rest_framework.permissions import IsAuthenticated

from drf_yasg.utils import swagger_auto_schema

from blog.articles.models import Article
from api.articles.serializers import ArticleDetailSerializer
from api.articles.permissions import ArticleAdministrationPermissions


class ArticleViewsetForVisitor(ReadOnlyModelViewSet):

    serializer_class = ArticleDetailSerializer

    @swagger_auto_schema(
        operation_description="Display the detail of an article ",
        responses={200: 'ArticleDetailSerializer'}
    )
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(
            request, *args, **kwargs)

    @swagger_auto_schema(
        operation_description="Display the list of articles",
        responses={200: 'ArticleDetailSerializer'}
        )
    def list(self):
        return super().list(self)

    def get_queryset(self):
        return Article.objects.filter(published=True)


class ArticleViewset(ModelViewSet):

    serializer_class = ArticleDetailSerializer
    filterset_fields = ['published']
    permission_classes = [IsAuthenticated, ArticleAdministrationPermissions]

    def get_queryset(self):
        return Article.objects.all()

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

    @swagger_auto_schema(
        operation_description="Display the list of articles",
        responses={200: 'ArticleDetailSerializer'}
        )
    def list(self):
        return super().list(self)

    @swagger_auto_schema(
        operation_description="Display the detail of an article ",
        responses={200: 'ArticleDetailSerializer'}
    )
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(
            request, *args, **kwargs)

    @swagger_auto_schema(
        operation_description="Create an article ",
        responses={200: 'ArticleDetailSerializer'}
    )
    def create(self, request, *args, **kwargs):
        return super().create(
            request, *args, **kwargs)

    @swagger_auto_schema(
        operation_description="Destroy an article ",
        responses={200: 'ArticleDetailSerializer'}
    )
    def destroy(self, request, *args, **kwargs):
        return super().destroy(
            request, *args, **kwargs)

    @swagger_auto_schema(
        operation_description="Modify an article ",
        responses={200: 'ArticleDetailSerializer'}
    )
    def update(self, request, *args, **kwargs):
        return super().update(
            request, *args, **kwargs)

    @swagger_auto_schema(
        operation_description="Partial modification of an article ",
        responses={200: 'ArticleDetailSerializer'}
    )
    def partial_update(self, request, *args, **kwargs):
        return super().partial_update(
            request, *args, **kwargs)

blog/articles/views.py
from datetime import date

from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)

from blog.articles.models import Article
from blog.articles.forms import CreationArticleForm


# To create an article
class CreationArticleView(CreateView):
    model = Article
    template_name = "articles/create_article.html"
    form_class = CreationArticleForm
    success_url = reverse_lazy("articles:all-articles")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title_part"] = _("Rédaction")
        context["submit_text"] = _("créer")
        return context

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user

        if form.cleaned_data.get("published"):
            form.instance.published_on = date.today()

        return super().form_valid(form)


creation_article_view = CreationArticleView.as_view()


# To display the articles.
class ArticleListView(ListView):
    model = Article
    context_object_name = "all_articles"
    template_name = "articles/all_articles.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        else:
            return queryset.filter(published=True)


articles_view = ArticleListView.as_view()


# To update an article
class UpdateArticleView(UpdateView):
    model = Article
    template_name = "articles/create_article.html"
    form_class = CreationArticleForm
    success_url = reverse_lazy("articles:all-articles")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title_part"] = _("Modification")
        context["submit_text"] = _("modifier")
        return context

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user

        if form.cleaned_data.get("published"):
            form.instance.published_on = date.today()
        else:
            form.instance.published_on = None

        return super().form_valid(form)


update_article_view = UpdateArticleView.as_view()


# To delete an article
class DeleteArticleView(DeleteView):
    model = Article
    template_name = "articles/confirmation_delete.html"
    context_object_name = "element"
    success_url = reverse_lazy("articles:all-articles")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title_subject"] = "un article"
        context["question"] = (
            f"""Voulez-vous supprimer l'article "{ context["element"].title }"
             ? """
        )
        previous_page = self.request.META.get("HTTP_REFERER", "/")
        context["previous_page"] = previous_page
        return context


delete_article_view = DeleteArticleView.as_view()

templates/articles/all_articles.html
{% extends 'base.html' %} 
{% load i18n %}

{% block title %}{% translate "Mes articles :" %}{% endblock title %} 


{% block content %}

<section class="text-center max-w-7xl mx-auto pt-36 md:pt-10 px-4 sm:px-6 lg:px-8">

  <!-- Le titre -->
  <div>
    <h1 class="text-4xl font-bold text-slate-900"> {% translate "Nos articles" %}</h1>
    <hr class="w-1/4 mt-5 mx-auto border-slate-900">
  </div>

  {% if user.is_authenticated %}
    {% include "articles/all_articles_admin.html" %}
  {% else %}
    {% include "articles/all_articles_visitor.html" %}
  {% endif %}

</section>
{% endblock content %} 

templates/articles/all_articles_admin.html
{% load i18n %}

  <!-- L'ajout' -->
  <div class="mt-3 mb-3 text-center">
    <a class="inline-block px-2 py-1 rounded-lg shadow-lg bg-violet-300 hover:bg-violet-200 focus:outline-none focus:shadow-outline text-xs text-white uppercase tracking-widest font-semibold" 
    href="{% url 'articles:creation-article' %}">{% translate "Ajouter un article" %}</a>  
  </div>


  <!-- Les articles -->
  
  <div class="mt-8 flex flex-wrap justify-center items-center flex-col  md:flex-row">

      <!-- un article -->
    {% for article in all_articles %}

    
      <div class="relative bg-sky-50 w-10/12 flex flex-col shadow-md ring-1 ring-slate-300 border border-slate-200 rounded-lg mt-7 mx-4 px-2 py-2 text-left">
        
        <!-- L'image' -->
        {% if article.image %}
        <div>
          <img class="mt6 rounded-lg shadow-xl h-44 w-full object-cover object-center"
            src="{{ article.image.url }}"
            alt="image de l'activité {{ article.title }}"
          />
        </div>

        {% endif %}

        <!-- Le détail -->
          <div class="px-2">
              <div class="relative">
                  <h2 class="mt-3 text-2xl font-bold text-slate-900"> {{ article.title }}</h2>
              </div>

              <p class="mt-1 text-slate-600 leading-tight">{{ article.content }}</p>
              
              <h3 class="mt-3 text-1xl font-semibold text-slate-900 ">{% translate "Publié le  :" %}
                  <span class="text-slate-600">{{ article.published_on }}</span>
              </h3>
          </div>
          <div class="flex justify-center mt-3 mb-3">
          <!-- Le bouton modifier -->
              <a class="inline-block px-2 py-1 mr-2 rounded-lg shadow-lg bg-violet-300 hover:bg-violet-200 focus:outline-none focus:shadow-outline text-xs text-white uppercase tracking-widest font-semibold" 
              href="{% url 'articles:article-detail-update' slug=article.slug %}" target ="_blank">{% translate "modifier" %}</a>  

          <!-- Le bouton supprimer -->
              <a class="inline-block px-2 py-1 ml-2 rounded-lg shadow-lg bg-red-300 hover:bg-red-200 focus:outline-none focus:shadow-outline text-xs text-white uppercase tracking-widest font-semibold" 
              href="{% url 'articles:article-detail-delete' slug=article.slug %}" target ="_blank">{% translate "supprimer" %}</a>  

          </div>
      </div>


    {% empty %}
        <div class=" bg-sky-50 min-w-fit flex flex-col shadow-md ring-1 ring-slate-300 border border-slate-200 rounded-lg mt-7 mx-4 px-2 py-2 text-left">
            <p class="pt-2 px-2 text-center">{% translate "Désolé, aucune article n'est disponible." %}</p>
        </div>
    {% endfor %}

  </div>

templates/articles/all_articles_visitor.html
{% load i18n %}


  <!-- Les articles -->
  
  <div class="mt-8 flex flex-wrap justify-center items-center flex-col  md:flex-row">

      <!-- un article -->
    {% for article in all_articles %}

    {% if article.published %}
    
      <div class="relative bg-sky-50 w-10/12 flex flex-col shadow-md ring-1 ring-slate-300 border border-slate-200 rounded-lg mt-7 mx-4 px-2 py-2 text-left">
        
        <!-- L'image' -->
        {% if article.image %}
        <div>
          <img class="mt6 rounded-lg shadow-xl h-44 w-full object-cover object-center"
            src="{{ article.image.url }}"
            alt="image de l'activité {{ article.title }}"
          />
        </div>

        {% endif %}

        <!-- Le détail -->

          <div class="px-2">
              <div class="relative">
                  <h2 class="mt-3 text-2xl font-bold text-slate-900"> {{ article.title }}</h2>
              </div>

              <p class="mt-1 text-slate-600 leading-tight">{{ article.content }}</p>
              
              <h3 class="mt-3 text-1xl font-semibold text-slate-900 ">{% translate "Publié le  :" %}
                  <span class="text-slate-600">{{ article.published_on }}</span>
              </h3>
          </div>
      </div>

    {% endif %}

    {% empty %}
        <div class=" bg-sky-50 min-w-fit flex flex-col shadow-md ring-1 ring-slate-300 border border-slate-200 rounded-lg mt-7 mx-4 px-2 py-2 text-left">
            <p class="pt-2 px-2 text-center">{% translate "Désolé, aucune article n'est disponible." %}</p>
        </div>
    {% endfor %}

  </div>

templates/articles/create_article.html
{% extends 'base.html' %} 
{% load i18n %}
{% load crispy_forms_tags %}


{% block title %}{% blocktranslate %} {{ title_part }} d'un article :{% endblocktranslate %}{% endblock title %} 


{% block content %}

{% if user.is_authenticated %}
<section class="text-center max-w-7xl mx-auto pt-36 pb-10 md:pt-10 px-4 sm:px-6 lg:px-8">

      <!-- Le titre -->
  <div>
    <h1 class="text-4xl font-bold text-gray-900 ">{% blocktranslate %} {{ title_part }} d'un article :{% endblocktranslate %}</h1>
    <hr class="w-1/4 mt-5 mx-auto border-slate-900">
  </div>

  <div class="mt-3 mb-3 text-center">
    <a class="inline-block px-2 py-1 rounded-lg shadow-lg bg-violet-300 hover:bg-violet-200 focus:outline-none focus:shadow-outline text-xs text-white uppercase tracking-widest font-semibold" 
    href="{% url 'articles:all-articles' %}">{% translate "Retour aux articles" %}</a>  
  </div>

    <div class=" bg-sky-50 shadow-md ring-1 ring-zinc-300 border border-t-gray-200 rounded-lg mt-7 mx-4 px-2 py-2 text-left">
        <form id="create-article-form" method="POST" enctype="multipart/form-data"  onsubmit="submission();">
          {% csrf_token %}
          {% comment %} {% crispy form %} {% endcomment %}
          {{ form|crispy }}
          <div class="flex justify-evenly">
            <button class="px-5 py-3 rounded-lg shadow-lg bg-sky-300 hover:bg-teal-300 focus:outline-none focus:shadow-outline text-sm text-white uppercase tracking-wider font-semibold" type="submit">{{ submit_text }}</button>
          </div>
          {% comment %} <input class="px-5 py-3 rounded-lg shadow-lg bg-sky-300 hover:bg-teal-300 focus:outline-none focus:shadow-outline text-sm text-white uppercase tracking-wider font-semibold" type="submit" value={{ submit_text }}> {% endcomment %}
        </form>

    </div>
  </section>
  {% endif %}
{% endblock content %}