api/events/urls.py
from django.urls import path, include
from rest_framework import routers

from api.events.views import EventViewset, EventViewsetForVisitor

# Ici nous créons notre routeur
router = routers.SimpleRouter()
# Puis lui déclarons une url basée sur le mot clé "event" et notre view
# afin que l’url générée soit celle que nous souhaitons ‘/api/event/’
router.register('events_admin', EventViewset, basename='events_admin')
router.register('events', EventViewsetForVisitor, basename='events')

urlpatterns = [
    path('api/', include(router.urls))
]

blog/events/urls.py
from django.urls import path
from blog.events.views import (events_view, creation_event_view,
                               update_event_view, delete_event_view)

app_name = "events"

urlpatterns = [
    path("events/", events_view, name="all-events"),
    path("events/creation/",
         creation_event_view,
         name="creation-event",
         ),
    path(
        "events/<slug:slug>/update/",
        update_event_view,
        name="event-detail-update",
        ),
    path(
        "events/<slug:slug>/delete/",
        delete_event_view,
        name="event-detail-delete",
        ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Configuration drf-yasg
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView)

# Configuration drf-yasg
schema_view = get_schema_view(
   openapi.Info(
      title="Blog Passion API",
      default_version='v1',
      description="An API to manage Blog Passion",
      contact=openapi.Contact(email="contact@blog-passion.fr"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.articles.urls")),
    path("events/", include("blog.events.urls")),
    path("users/", include("blog.users.urls")),
    path("contacts/", include("blog.contacts.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(),
         name='token_refresh'),
    path("", include("api.articles.urls")),
    path("", include('api.users.urls')),
    path("", include("api.events.urls")),
    path("", include("api.contacts.urls")),
    # Configuration drf-yasg
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0),
         name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0),
         name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),
         name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/events/models.py
from django.db import models
from django.conf import settings
from django_extensions.db.fields import AutoSlugField
from django.utils.translation import gettext_lazy as _


from PIL import Image


class Event(models.Model):
    """Each event will be registered here.
    """

    title = models.CharField(_("titre"), max_length=200)
    slug = AutoSlugField(
        "event slug",
        populate_from=["title"],
        unique=True,
    )
    content = models.TextField(_("description"), blank=True)
    image = models.ImageField(
        _("Image de l'événement"),
        upload_to="event/images/events",
        blank=True,
        null=True,
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="events",
        verbose_name=_("auteur"),
    )
    date_begin = models.DateField(
        _("date de début"),
        blank=True,
        null=True,
    )
    date_finish = models.DateField(
        _("date de fin"),
        blank=True,
        null=True,
    )
    published_on = models.DateField(_("publié le"), blank=True, null=True)
    published = models.BooleanField(_("publié"), default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    IMAGE_MAX_SIZE = (400, 150)

    class Meta:
        verbose_name_plural = _("événements")
        ordering = ['-published_on']

    def __str__(self):
        return self.title

    # Adaptation du format de l'image à un max définit en IMAGE_MAX_SIZE
    # A placer dans le formulaire
    def resize_image(self):
        with Image.open(self.image) as image:
            image.thumbnail(self.IMAGE_MAX_SIZE)
            image.save(self.image.path)

blog/events/forms.py
from django import forms

from blog.events.models import Event


class CreationEventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = [
            "title",
            "content",
            "image",
            "date_begin",
            "date_finish",
            "published",
        ]

api/events/views.py
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from rest_framework.permissions import IsAuthenticated

from drf_yasg.utils import swagger_auto_schema

from blog.events.models import Event
from api.events.serializers import EventDetailSerializer
from api.events.permissions import EventAdministrationPermissions


class EventViewsetForVisitor(ReadOnlyModelViewSet):

    serializer_class = EventDetailSerializer

    def get_queryset(self):
        return Event.objects.filter(published=True)


class EventViewset(ModelViewSet):

    serializer_class = EventDetailSerializer
    filterset_fields = ['published']
    permission_classes = [IsAuthenticated, EventAdministrationPermissions]

    def get_queryset(self):
        return Event.objects.all()

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

    @swagger_auto_schema(
        operation_description="Display the list of articles",
        responses={200: 'ArticleDetailSerializer'}
        )
    def list(self):
        return super().list(self)

    @swagger_auto_schema(
        operation_description="Display the detail of an event ",
        responses={200: 'EventDetailSerializer'}
    )
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(
            request, *args, **kwargs)

    @swagger_auto_schema(
        operation_description="Create an event ",
        responses={200: 'EventDetailSerializer'}
    )
    def create(self, request, *args, **kwargs):
        return super().create(
            request, *args, **kwargs)

    @swagger_auto_schema(
        operation_description="Destroy an event ",
        responses={200: 'EventDetailSerializer'}
    )
    def destroy(self, request, *args, **kwargs):
        return super().destroy(
            request, *args, **kwargs)

    @swagger_auto_schema(
        operation_description="Modify an event ",
        responses={200: 'EventDetailSerializer'}
    )
    def update(self, request, *args, **kwargs):
        return super().update(
            request, *args, **kwargs)

    @swagger_auto_schema(
        operation_description="Partial modification of an event ",
        responses={200: 'EventDetailSerializer'}
    )
    def partial_update(self, request, *args, **kwargs):
        return super().partial_update(
            request, *args, **kwargs)

blog/events/views.py
from datetime import date

from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)

from blog.events.models import Event
from blog.events.forms import CreationEventForm


# To create an article
class CreationEventView(CreateView):
    model = Event
    template_name = "events/create_event.html"
    form_class = CreationEventForm
    success_url = reverse_lazy("events:all-events")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title_part"] = _("Création")
        context["submit_text"] = _("créer")
        return context

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user

        if form.cleaned_data.get("published"):
            form.instance.published_on = date.today()

        return super().form_valid(form)


creation_event_view = CreationEventView.as_view()


# To display the events.
class EventListView(ListView):
    model = Event
    context_object_name = "all_events"
    template_name = "events/all_events.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        else:
            return queryset.filter(published=True)


events_view = EventListView.as_view()


# To update an event
class UpdateEventView(UpdateView):
    model = Event
    template_name = "events/create_event.html"
    form_class = CreationEventForm
    success_url = reverse_lazy("events:all-events")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title_part"] = _("Modification")
        context["submit_text"] = _("modifier")
        return context

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user

        if form.cleaned_data.get("published"):
            form.instance.published_on = date.today()
        else:
            form.instance.published_on = None

        return super().form_valid(form)


update_event_view = UpdateEventView.as_view()


# To delete an event
class DeleteEventView(DeleteView):
    model = Event
    template_name = "events/confirmation_delete.html"
    context_object_name = "element"
    success_url = reverse_lazy("events:all-events")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title_subject"] = "un événement"
        context["question"] = (
            f"""Voulez-vous supprimer l'événement
            "{ context["element"].title }" ? """
        )
        previous_page = self.request.META.get("HTTP_REFERER", "/")
        context["previous_page"] = previous_page
        return context


delete_event_view = DeleteEventView.as_view()

templates/events/all_events.html
{% extends 'base.html' %} 
{% load i18n %}

{% block title %}{% translate "Nos événements :" %}{% endblock title %} 


{% block content %}

<section class="text-center max-w-7xl mx-auto pt-36 md:pt-10 px-4 sm:px-6 lg:px-8">

  <!-- Le titre -->
  <div>
    <h1 class="text-4xl font-bold text-slate-900"> {% translate "Nos événements" %}</h1>
    <hr class="w-1/4 mt-5 mx-auto border-slate-900">
  </div>

  {% if user.is_authenticated %}
    {% include "events/all_events_admin.html" %}
  {% else %}
    {% include "events/all_events_visitor.html" %}
  {% endif %}

</section>
{% endblock content %} 

templates/events/all_events_admin.html
{% load i18n %}



    <div class="mt-3 mb-3 text-center">
        <a class="inline-block px-2 py-1 rounded-lg shadow-lg bg-violet-300 hover:bg-violet-200 focus:outline-none focus:shadow-outline text-xs text-white uppercase tracking-widest font-semibold" 
        href="{% url 'events:creation-event' %}">{% translate "Ajouter un événement" %}</a>  
    </div>

  <!-- Les évènements -->
  
  <div class="mt-8 flex flex-wrap justify-center items-center flex-col  md:flex-row">

      <!-- un évènement -->
    {% for event in all_events %}
    
    <div class="relative bg-sky-50 min-h-[450px] w-80 flex flex-col shadow-md ring-1 ring-slate-300 border border-slate-200 rounded-lg mt-7 mx-4 px-2 py-2 text-left">
      
      <!-- 1 L'image' -->
      {% if event.image %}
      <div>
        <img class="mt6 rounded-lg shadow-xl h-44 w-full object-cover object-center"
          src="{{ event.image.url }}"
          alt="image de l'activité {{ event.title }}"
        />
      </div>

      {% endif %}

      <!-- 2 Le détail -->
      <div class="px-2">
        <div class="relative">
          <h2 class="mt-3 text-2xl font-bold text-slate-900"> {{ event.title }}</h2>

        </div>

          <h3 class="mt-3 text-1xl font-semibold text-slate-900">{% translate "Description :" %} </h3>
          <p class="mt-1 text-slate-600 leading-tight line-clamp-2 hover:line-clamp-none">{{ event.content }}</p>
          

          {% if event.date_begin %}  
          <h3 class="mt-3 text-1xl font-semibold text-slate-900 ">{% translate "Début de l'événement :" %}
            <span class="text-slate-600"> {{ event.date_begin }}</span>
          </h3>
          {% endif %}

          {% if event.date_finish %}  
          <h3 class="mt-3 text-1xl font-semibold text-slate-900 ">{% translate "Fin de l'événement :" %}
            <span class="text-slate-600"> {{ event.date_finish }}</span>
          </h3>
          {% endif %}

          <h3 class="mt-3 text-1xl font-semibold text-slate-900 ">{% translate "Publié le  :" %}
            <span class="text-slate-600">{{ event.published_on }}</span>
          </h3>


        
      </div>
      <div class="flex justify-center mt-3 mb-3">
        <!-- 4 Le bouton modifier -->
          <a class="inline-block px-2 py-1 mr-2 rounded-lg shadow-lg bg-violet-300 hover:bg-violet-200 focus:outline-none focus:shadow-outline text-xs text-white uppercase tracking-widest font-semibold" 
          href="{% url 'events:event-detail-update' slug=event.slug %}" target ="_blank">{% translate "modifier" %}</a>  

        <!-- 3 Le bouton supprimer -->
          <a class="inline-block px-2 py-1 ml-2 rounded-lg shadow-lg bg-red-300 hover:bg-red-200 focus:outline-none focus:shadow-outline text-xs text-white uppercase tracking-widest font-semibold" 
          href="{% url 'events:event-detail-delete' slug=event.slug %}" target ="_blank">{% translate "supprimer" %}</a>  
      </div>
    </div>

    {% empty %}
        <div class=" bg-sky-50 min-w-fit flex flex-col shadow-md ring-1 ring-slate-300 border border-slate-200 rounded-lg mt-7 mx-4 px-2 py-2 text-left">
            <p class="pt-2 px-2 text-center">{% translate "Désolé, aucun événement n'est encore planifié." %}</p>
        </div>
    {% endfor %}

  </div>

templates/events/all_events_visitor.html
{% load i18n %}



  <!-- Les évènements -->
  
  <div class="mt-8 flex flex-wrap justify-center items-center flex-col  md:flex-row">

      <!-- un évènement -->
    {% for event in all_events %}

    {% if event.published %}
    
      <div class="relative bg-sky-50 min-h-[450px] w-80 flex flex-col shadow-md ring-1 ring-slate-300 border border-slate-200 rounded-lg mt-7 mx-4 px-2 py-2 text-left">
        
        <!-- 1 L'image' -->
        {% if event.image %}
        <div>
          <img class="mt6 rounded-lg shadow-xl h-44 w-full object-cover object-center"
            src="{{ event.image.url }}"
            alt="image de l'activité {{ event.title }}"
          />
        </div>

        {% endif %}

        <!-- 2 Le détail -->
        <div class="px-2">
          <div class="relative">
            <h2 class="mt-3 text-2xl font-bold text-slate-900"> {{ event.title }}</h2>

          </div>

            <h3 class="mt-3 text-1xl font-semibold text-slate-900">{% translate "Description :" %} </h3>
            <p class="mt-1 text-slate-600 leading-tight line-clamp-2 hover:line-clamp-none">{{ event.content }}</p>
            

            {% if event.date_begin %}  
            <h3 class="mt-3 text-1xl font-semibold text-slate-900 ">{% translate "Début de l'événement :" %}
              <span class="text-slate-600"> {{ event.date_begin }}</span>
            </h3>
            {% endif %}

            {% if event.date_finish %}  
            <h3 class="mt-3 text-1xl font-semibold text-slate-900 ">{% translate "Fin de l'événement :" %}
              <span class="text-slate-600"> {{ event.date_finish }}</span>
            </h3>
            {% endif %}

            <h3 class="mt-3 text-1xl font-semibold text-slate-900 ">{% translate "Publié le  :" %}
              <span class="text-slate-600">{{ event.published_on }}</span>
            </h3>
        </div>
      </div>
    {% endif %}

      
    {% empty %}
        <div class=" bg-sky-50 min-w-fit flex flex-col shadow-md ring-1 ring-slate-300 border border-slate-200 rounded-lg mt-7 mx-4 px-2 py-2 text-left">
            <p class="pt-2 px-2 text-center">{% translate "Désolé, aucun événement n'est encore planifié." %}</p>
        </div>
    {% endfor %}

  </div>

templates/events/confirmation_delete.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}Supprimer {{ title_subject }}{% endblock title %} 


{% block content %}

<section class="text-center max-w-7xl mx-auto pt-36 md:pt-10 px-4 sm:px-6 lg:px-8">

<div " bg-sky-50 shadow-md ring-1 ring-zinc-300 border border-t-gray-200 rounded-lg mt-7 mx-4 px-2 py-2 text-left">
    <div class="mt-16 mb-16 flex flex-col items-center mx-auto">

        <div>
            <img class=""
            src="{% static 'images/warning.png' %}"
            alt="picto warning" 
            >
        </div>
        <form method="POST">
            {% csrf_token %}
            <p class="text-center"> {{ question }} </p>
            <button class="inline-block w-32 mt-2 md:mt-5 px-2 py-1 ml-2 rounded-lg shadow-lg bg-red-300 hover:bg-red-200 focus:outline-none focus:shadow-outline text-xs text-white uppercase tracking-widest font-semibold"
             type="submit">Supprimer</button>
            <a href="{{ previous_page }}"><button class="inline-block w-32 mt-2 md:mt-5 px-2 py-1 ml-2 rounded-lg shadow-lg bg-teal-300 hover:bg-teal-200 focus:outline-none focus:shadow-outline text-xs text-white uppercase tracking-widest font-semibold"
                type="button">Retour</button></a>
        </form>
    </div>

</div>
</section>
{% endblock content %} 

templates/events/create_event.html
{% extends 'base.html' %} 
{% load i18n %}
{% load crispy_forms_tags %}


{% block title %}{% blocktranslate %} {{ title_part }} d'un événement :{% endblocktranslate %}{% endblock title %} 


{% block content %}

{% if user.is_authenticated %}
<section class="text-center max-w-7xl mx-auto pt-36 pb-10 md:pt-10 px-4 sm:px-6 lg:px-8">

      <!-- Le titre -->
  <div>
    <h1 class="text-4xl font-bold text-gray-900 ">{% blocktranslate %} {{ title_part }} d'un évènement :{% endblocktranslate %}</h1>
    <hr class="w-1/4 mt-5 mx-auto border-slate-900">
  </div>

  <div class="mt-3 mb-3 text-center">
    <a class="inline-block px-2 py-1 rounded-lg shadow-lg bg-violet-300 hover:bg-violet-200 focus:outline-none focus:shadow-outline text-xs text-white uppercase tracking-widest font-semibold" 
    href="{% url 'events:all-events' %}">{% translate "Retour aux événements" %}</a>  
  </div>

    <div class=" bg-sky-50 shadow-md ring-1 ring-zinc-300 border border-t-gray-200 rounded-lg mt-7 mx-4 px-2 py-2 text-left">
        <form id="create-event-form" method="POST" enctype="multipart/form-data"  onsubmit="submission();">
          {% csrf_token %}
          {{ form|crispy }}
          <div class="flex justify-evenly">
            <button class="px-5 py-3 rounded-lg shadow-lg bg-sky-300 hover:bg-teal-300 focus:outline-none focus:shadow-outline text-sm text-white uppercase tracking-wider font-semibold" type="submit">{{ submit_text }}</button>
          </div>
        </form>

    </div>
  </section>
  {% endif %}
{% endblock content %}